library(stringr)

book_df <- read.csv("data/le_morte_darthur.csv", stringsAsFactors = F)

book_df$id <- c(1:nrow(book_df))
book_df$text_lower <- tolower(book_df$text)
book_df <- book_df[,c('id','text_lower')]

# Main characters
book_df$arthur <- grepl('arthur',book_df$text_lower)
book_df$merlin <- grepl('merlin',book_df$text_lower)
book_df$guenever <- grepl('guenever',book_df$text_lower)
book_df$launcelot <- grepl('launcelot',book_df$text_lower)
book_df$lady_of_the_lake <- grepl('lady of the lake|damosel of the lake',book_df$text_lower)
book_df$galahad <- grepl('galahad',book_df$text_lower)
book_df$mordred <- grepl('mordred',book_df$text_lower)
book_df$tristram <- grepl('tristram',book_df$text_lower)

# Additional Characters
book_df$ector <- grepl('ector',book_df$text_lower)
book_df$igraine <- grepl('igraine',book_df$text_lower)
book_df$morgan <- grepl('morgan',book_df$text_lower)
book_df$uther <- grepl('uther',book_df$text_lower)
book_df$agravaine <- grepl('agravaine',book_df$text_lower)
book_df$alisander <- grepl('alisander',book_df$text_lower)
book_df$andred <- grepl('andred',book_df$text_lower)
book_df$balin <- grepl('balin',book_df$text_lower)
book_df$beaumains <- grepl('beaumains',book_df$text_lower)
book_df$bedivere <- grepl('bedivere',book_df$text_lower)
book_df$blamore <- grepl('blamore',book_df$text_lower)
book_df$bleoberis <- grepl('bleoberis',book_df$text_lower)
book_df$bors <- grepl('bors',book_df$text_lower)
book_df$boudwin <- grepl('boudwin',book_df$text_lower)
book_df$breunor <- grepl('breunor',book_df$text_lower)
book_df$colgrevance <- grepl('colgrevance',book_df$text_lower)
book_df$cote <- grepl('cote',book_df$text_lower)
book_df$dinadan <- grepl('dinadan',book_df$text_lower)
book_df$elias <- grepl('elias',book_df$text_lower)
book_df$galahalt <- grepl('galahalt',book_df$text_lower)
book_df$gareth <- grepl('gareth',book_df$text_lower)
book_df$gawaine <- grepl('gawaine',book_df$text_lower)
book_df$isoud <- grepl('isoud',book_df$text_lower)
book_df$kay <- grepl('kay',book_df$text_lower)
book_df$king_mark <- grepl('king mark',book_df$text_lower)
book_df$king_pellinore <- grepl('king pellinore',book_df$text_lower)
book_df$lionel <- grepl('lionel',book_df$text_lower)
book_df$mador <- grepl('mador',book_df$text_lower)
book_df$marhaus <- grepl('marhaus',book_df$text_lower)
book_df$meliagrance <- grepl('meliagrance',book_df$text_lower)
book_df$nabon <- grepl('nabon',book_df$text_lower)
book_df$palomides <- grepl('palomides',book_df$text_lower)
book_df$percivale <- grepl('percivale',book_df$text_lower)
book_df$segwarides <- grepl('segwarides',book_df$text_lower)
book_df$tor <- grepl('sir tor',book_df$text_lower)
book_df$uwaine <- grepl('uwaine',book_df$text_lower)
book_df$aglovale <- grepl('aglovale',book_df$text_lower)
book_df$bragwaine <- grepl('bragwaine',book_df$text_lower)
book_df$elaine <- grepl('elaine',book_df$text_lower)
book_df$gaheris <- grepl('gaheris',book_df$text_lower)
book_df$galihodin <- grepl('galihodin',book_df$text_lower)
book_df$griflet <- grepl('griflet',book_df$text_lower)
book_df$lanceor <- grepl('lanceor',book_df$text_lower)
book_df$lancelot <- grepl('lancelot',book_df$text_lower)
book_df$linet <- grepl('linet',book_df$text_lower)
book_df$lamorak <- grepl('lamorak',book_df$text_lower)
book_df$frol <- grepl('frol',book_df$text_lower)
book_df$pelleas <- grepl('pelleas',book_df$text_lower)
book_df$pervivale <- grepl('pervivale',book_df$text_lower)
book_df$solomon <- grepl('solomon',book_df$text_lower)

# Other tales
book_df$jousting <- grepl('joust',book_df$text_lower)
book_df$beasts <- grepl(' dragon|giants|questing beast',book_df$text_lower)
book_df$holy_grail <- grepl('sangreal',book_df$text_lower)
book_df$excalibur_and_scabbard <- grepl('scabbard|excalibur',book_df$text_lower)


# Converting TRUE & FALSE to NULL & 1 for Tableau Tagging
book_df$arthur <- gsub('FALSE',1,gsub('TRUE','',book_df$arthur))
book_df$merlin <- gsub('FALSE',1,gsub('TRUE','',book_df$merlin))
book_df$guenever <- gsub('FALSE',1,gsub('TRUE','',book_df$guenever))
book_df$launcelot <- gsub('FALSE',1,gsub('TRUE','',book_df$launcelot))
book_df$lady_of_the_lake <- gsub('FALSE',1,gsub('TRUE','',book_df$lady_of_the_lake))
book_df$galahad <- gsub('FALSE',1,gsub('TRUE','',book_df$galahad))
book_df$mordred <- gsub('FALSE',1,gsub('TRUE','',book_df$mordred))
book_df$tristram <- gsub('FALSE',1,gsub('TRUE','',book_df$tristram))

book_df$ector <- gsub('FALSE',1,gsub('TRUE','',book_df$ector))
book_df$igraine <- gsub('FALSE',1,gsub('TRUE','',book_df$igraine))
book_df$morgan <- gsub('FALSE',1,gsub('TRUE','',book_df$morgan))
book_df$uther <- gsub('FALSE',1,gsub('TRUE','',book_df$uther))
book_df$agravaine <- gsub('FALSE',1,gsub('TRUE','',book_df$agravaine))
book_df$alisander <- gsub('FALSE',1,gsub('TRUE','',book_df$alisander))
book_df$andred <- gsub('FALSE',1,gsub('TRUE','',book_df$andred))
book_df$balin <- gsub('FALSE',1,gsub('TRUE','',book_df$balin))
book_df$beaumains <- gsub('FALSE',1,gsub('TRUE','',book_df$beaumains))
book_df$bedivere <- gsub('FALSE',1,gsub('TRUE','',book_df$bedivere))
book_df$blamore <- gsub('FALSE',1,gsub('TRUE','',book_df$blamore))
book_df$bleoberis <- gsub('FALSE',1,gsub('TRUE','',book_df$bleoberis))
book_df$bors <- gsub('FALSE',1,gsub('TRUE','',book_df$bors))
book_df$boudwin <- gsub('FALSE',1,gsub('TRUE','',book_df$boudwin))
book_df$breunor <- gsub('FALSE',1,gsub('TRUE','',book_df$breunor))
book_df$colgrevance <- gsub('FALSE',1,gsub('TRUE','',book_df$colgrevance))
book_df$cote <- gsub('FALSE',1,gsub('TRUE','',book_df$cote))
book_df$dinadan <- gsub('FALSE',1,gsub('TRUE','',book_df$dinadan))
book_df$elias <- gsub('FALSE',1,gsub('TRUE','',book_df$elias))
book_df$galahalt <- gsub('FALSE',1,gsub('TRUE','',book_df$galahalt))
book_df$gareth <- gsub('FALSE',1,gsub('TRUE','',book_df$gareth))
book_df$gawaine <- gsub('FALSE',1,gsub('TRUE','',book_df$gawaine))
book_df$isoud <- gsub('FALSE',1,gsub('TRUE','',book_df$isoud))
book_df$kay <- gsub('FALSE',1,gsub('TRUE','',book_df$kay))
book_df$king_mark <- gsub('FALSE',1,gsub('TRUE','',book_df$king_mark))
book_df$king_pellinore <- gsub('FALSE',1,gsub('TRUE','',book_df$king_pellinore))
book_df$lionel <- gsub('FALSE',1,gsub('TRUE','',book_df$lionel))
book_df$mador <- gsub('FALSE',1,gsub('TRUE','',book_df$mador))
book_df$marhaus <- gsub('FALSE',1,gsub('TRUE','',book_df$marhaus))
book_df$meliagrance <- gsub('FALSE',1,gsub('TRUE','',book_df$meliagrance))
book_df$nabon <- gsub('FALSE',1,gsub('TRUE','',book_df$nabon))
book_df$palomides <- gsub('FALSE',1,gsub('TRUE','',book_df$palomides))
book_df$percivale <- gsub('FALSE',1,gsub('TRUE','',book_df$percivale))
book_df$segwarides <- gsub('FALSE',1,gsub('TRUE','',book_df$segwarides))
book_df$tor <- gsub('FALSE',1,gsub('TRUE','',book_df$tor))
book_df$uwaine <- gsub('FALSE',1,gsub('TRUE','',book_df$uwaine))
book_df$aglovale <- gsub('FALSE',1,gsub('TRUE','',book_df$aglovale))
book_df$bragwaine <- gsub('FALSE',1,gsub('TRUE','',book_df$bragwaine))
book_df$elaine <- gsub('FALSE',1,gsub('TRUE','',book_df$elaine))
book_df$gaheris <- gsub('FALSE',1,gsub('TRUE','',book_df$gaheris))
book_df$galihodin <- gsub('FALSE',1,gsub('TRUE','',book_df$galihodin))
book_df$griflet <- gsub('FALSE',1,gsub('TRUE','',book_df$griflet))
book_df$lanceor <- gsub('FALSE',1,gsub('TRUE','',book_df$lanceor))
book_df$lancelot <- gsub('FALSE',1,gsub('TRUE','',book_df$lancelot))
book_df$linet <- gsub('FALSE',1,gsub('TRUE','',book_df$linet))
book_df$lamorak <- gsub('FALSE',1,gsub('TRUE','',book_df$lamorak))
book_df$frol <- gsub('FALSE',1,gsub('TRUE','',book_df$frol))
book_df$pelleas <- gsub('FALSE',1,gsub('TRUE','',book_df$pelleas))
book_df$pervivale <- gsub('FALSE',1,gsub('TRUE','',book_df$pervivale))
book_df$solomon <- gsub('FALSE',1,gsub('TRUE','',book_df$solomon))

book_df$jousting <- gsub('FALSE',1,gsub('TRUE','',book_df$jousting))
book_df$beasts <- gsub('FALSE',1,gsub('TRUE','',book_df$beasts))
book_df$holy_grail <- gsub('FALSE',1,gsub('TRUE','',book_df$holy_grail))
book_df$excalibur_and_scabbard <- gsub('FALSE',1,gsub('TRUE','',book_df$excalibur_and_scabbard))

write.csv(book_df,'data/character_tagging.csv',row.names = F)
