library(stringr)

book_df <- read.csv("data/le_morte_darthur.csv", stringsAsFactors = F)

book_df$id <- c(1:nrow(book_df))
book_df$text_lower <- tolower(book_df$text)

book_df$arthur <- grepl('arthur',book_df$text_lower)
book_df$merlin <- grepl('merlin',book_df$text_lower)
book_df$guenever <- grepl('guenever',book_df$text_lower)
book_df$launcelot <- grepl('launcelot',book_df$text_lower)
book_df$lady_of_the_lake <- grepl('lady of the lake|damosel of the lake',book_df$text_lower)
book_df$galahad <- grepl('galahad',book_df$text_lower)
book_df$ector <- grepl('ector',book_df$text_lower)
book_df$igraine <- grepl('igraine',book_df$text_lower)
book_df$morgan <- grepl('morgan',book_df$text_lower)
book_df$uther <- grepl('uther',book_df$text_lower)
book_df$agravaine <- grepl('agravaine',book_df$text_lower)
book_df$alisander <- grepl('alisander',book_df$text_lower)
book_df$andred <- grepl('andred',book_df$text_lower)
book_df$balin <- grepl('balin',book_df$text_lower)
book_df$beaumains <- grepl('beaumains',book_df$text_lower)
book_df$bedivere <- grepl('bedivere',book_df$text_lower)
book_df$blamore <- grepl('blamore',book_df$text_lower)
book_df$bleoberis <- grepl('bleoberis',book_df$text_lower)
book_df$bors <- grepl('bors',book_df$text_lower)
book_df$boudwin <- grepl('boudwin',book_df$text_lower)
book_df$breunor <- grepl('breunor',book_df$text_lower)
book_df$colgrevance <- grepl('colgrevance',book_df$text_lower)
book_df$cote <- grepl('cote',book_df$text_lower)
book_df$dinadan <- grepl('dinadan',book_df$text_lower)
book_df$elias <- grepl('elias',book_df$text_lower)
book_df$galahalt <- grepl('galahalt',book_df$text_lower)
book_df$gareth <- grepl('gareth',book_df$text_lower)
book_df$gawaine <- grepl('gawaine',book_df$text_lower)
book_df$isoud <- grepl('isoud',book_df$text_lower)
book_df$kay <- grepl('kay',book_df$text_lower)
book_df$king_mark <- grepl('king mark',book_df$text_lower)
book_df$king_pellinore <- grepl('king pellinore',book_df$text_lower)
book_df$lionel <- grepl('lionel',book_df$text_lower)
book_df$mador <- grepl('mador',book_df$text_lower)
book_df$marhaus <- grepl('marhaus',book_df$text_lower)
book_df$meliagrance <- grepl('meliagrance',book_df$text_lower)
book_df$mordred <- grepl('mordred',book_df$text_lower)
book_df$nabon <- grepl('nabon',book_df$text_lower)
book_df$palomides <- grepl('palomides',book_df$text_lower)
book_df$percivale <- grepl('percivale',book_df$text_lower)
book_df$segwarides <- grepl('segwarides',book_df$text_lower)
book_df$tor <- grepl('tor',book_df$text_lower)
book_df$tristram <- grepl('tristram',book_df$text_lower)
book_df$uwaine <- grepl('uwaine',book_df$text_lower)
book_df$aglovale <- grepl('aglovale',book_df$text_lower)
book_df$bragwaine <- grepl('bragwaine',book_df$text_lower)
book_df$elaine <- grepl('elaine',book_df$text_lower)
book_df$gaheris <- grepl('gaheris',book_df$text_lower)
book_df$galihodin <- grepl('galihodin',book_df$text_lower)
book_df$griflet <- grepl('griflet',book_df$text_lower)
book_df$lanceor <- grepl('lanceor',book_df$text_lower)
book_df$lancelot <- grepl('lancelot',book_df$text_lower)
book_df$linet <- grepl('linet',book_df$text_lower)
book_df$lamorak <- grepl('lamorak',book_df$text_lower)
book_df$frol <- grepl('frol',book_df$text_lower)
book_df$pelleas <- grepl('pelleas',book_df$text_lower)
book_df$pervivale <- grepl('pervivale',book_df$text_lower)
book_df$solomon <- grepl('solomon',book_df$text_lower)

